#!/usr/bin/env python

import sys
import re

msg = open(sys.argv[1], 'r').read()
if not re.match(r'\[\d+] .+', msg):
    print('Incorrect commit message!!!')
    print('Use this as example:')
    print('"[34] Made some stuff"')
    sys.exit(-1)
